# This is a basic workflow to help you get started with Actions

name: upload
on:
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p output/{a,b}
          echo 'a file text' > output/a/txt
          echo 'b file text' > output/b/txt
      - uses: actions/upload-artifact@v3
        with:
          name: output_artifact
          path: output
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -R
