# This is a basic workflow to help you get started with Actions

name: upload
on:
  workflow_dispatch:
jobs:
  upload:
    strategy:
      matrix:
        var:
          - one
          - two
          - three
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p output/${{ matrix.var }}
          echo 'file content' > output/${{ matrix.var }}/file.txt
      - uses: actions/upload-artifact@v3
        with:
          path: output
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: download_location
      - run: ls -R
